#!/usr/bin/env bash
# Regenerates projects/index.txt — the list of project files the site loads.
#
# You only need this because GitHub Pages serves no directory listings, so
# the browser can't discover the folder's contents on its own. Run it after
# adding or renaming a project file:
#
#     ./make-index.sh
#
# The GitHub Action in .github/workflows/project-index.yml runs it for you
# on every push, so in practice you can just add a file and push.
set -euo pipefail
cd "$(dirname "$0")"

out=projects/index.txt
{
  echo "# Generated by make-index.sh — do not edit by hand."
  echo "# Every .txt in projects/ except _template.txt and other _ files."
  for f in projects/*.txt; do
    base=$(basename "$f")
    case "$base" in
      _*|index.txt) continue ;;
    esac
    echo "$base"
  done
} > "$out"

echo "Wrote $out:"
grep -v '^#' "$out" | sed 's/^/  /'
